name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Auth to DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Starting login process"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Ending login process"
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
